package com.sis.db;

import java.sql.*;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.Executor;

class PooledConnection implements Connection {

    private final Connection        delegate;
    private final BlockingQueue<Connection> pool;

    PooledConnection(Connection delegate, BlockingQueue<Connection> pool) {
        this.delegate = delegate;
        this.pool     = pool;
    }

    /** Returns this connection to the pool instead of closing it. */
    @Override
    public void close() {
        try {
            if (delegate.isClosed()) {
                return;
            }
            if (!delegate.getAutoCommit()) {
                try { delegate.rollback(); } catch (SQLException ignored) {}
                delegate.setAutoCommit(true);
            }
            if (delegate.isReadOnly()) {
                delegate.setReadOnly(false);
            }
            delegate.clearWarnings();
            if (!pool.offer(delegate)) {
                closeQuietly(delegate);
            }
        } catch (SQLException e) {
            closeQuietly(delegate);
        }
    }

    private static void closeQuietly(Connection c) {
        try { if (c != null) c.close(); } catch (SQLException ignored) {}
    }

    @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }

    // ── Statement factories ───────────────────────────────────────────────────
    @Override public Statement        createStatement()  throws SQLException { return delegate.createStatement(); }
    @Override public PreparedStatement prepareStatement(String sql) throws SQLException { return delegate.prepareStatement(sql); }
    @Override public CallableStatement prepareCall(String sql)      throws SQLException { return delegate.prepareCall(sql); }
    @Override public Statement        createStatement(int t, int c)      throws SQLException { return delegate.createStatement(t, c); }
    @Override public Statement        createStatement(int t, int c, int h) throws SQLException { return delegate.createStatement(t, c, h); }
    @Override public PreparedStatement prepareStatement(String sql, int t, int c) throws SQLException { return delegate.prepareStatement(sql, t, c); }
    @Override public CallableStatement prepareCall(String sql, int t, int c)      throws SQLException { return delegate.prepareCall(sql, t, c); }
    @Override public PreparedStatement prepareStatement(String sql, int t, int c, int h) throws SQLException { return delegate.prepareStatement(sql, t, c, h); }
    @Override public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)  throws SQLException { return delegate.prepareStatement(sql, autoGeneratedKeys); }
    @Override public PreparedStatement prepareStatement(String sql, int[] columnIndexes)    throws SQLException { return delegate.prepareStatement(sql, columnIndexes); }
    @Override public PreparedStatement prepareStatement(String sql, String[] columnNames)   throws SQLException { return delegate.prepareStatement(sql, columnNames); }
    @Override public CallableStatement prepareCall(String sql, int t, int c, int h)         throws SQLException { return delegate.prepareCall(sql, t, c, h); }

    // ── Transaction ──────────────────────────────────────────────────────────
    @Override public void   commit()              throws SQLException { delegate.commit(); }
    @Override public void   rollback()            throws SQLException { delegate.rollback(); }
    @Override public void   rollback(Savepoint s) throws SQLException { delegate.rollback(s); }
    @Override public boolean getAutoCommit()       throws SQLException { return delegate.getAutoCommit(); }
    @Override public void   setAutoCommit(boolean b) throws SQLException { delegate.setAutoCommit(b); }
    @Override public Savepoint setSavepoint()             throws SQLException { return delegate.setSavepoint(); }
    @Override public Savepoint setSavepoint(String name)  throws SQLException { return delegate.setSavepoint(name); }
    @Override public void   releaseSavepoint(Savepoint s) throws SQLException { delegate.releaseSavepoint(s); }

    // ── Metadata & misc ──────────────────────────────────────────────────────
    @Override public DatabaseMetaData getMetaData()     throws SQLException { return delegate.getMetaData(); }
    @Override public String  nativeSQL(String sql)       throws SQLException { return delegate.nativeSQL(sql); }
    @Override public boolean isReadOnly()                throws SQLException { return delegate.isReadOnly(); }
    @Override public void   setReadOnly(boolean ro)      throws SQLException { delegate.setReadOnly(ro); }
    @Override public String  getCatalog()                throws SQLException { return delegate.getCatalog(); }
    @Override public void   setCatalog(String c)         throws SQLException { delegate.setCatalog(c); }
    @Override public int    getTransactionIsolation()    throws SQLException { return delegate.getTransactionIsolation(); }
    @Override public void   setTransactionIsolation(int l) throws SQLException { delegate.setTransactionIsolation(l); }
    @Override public SQLWarning getWarnings()            throws SQLException { return delegate.getWarnings(); }
    @Override public void   clearWarnings()              throws SQLException { delegate.clearWarnings(); }
    @Override public Map<String, Class<?>> getTypeMap()  throws SQLException { return delegate.getTypeMap(); }
    @Override public void   setTypeMap(Map<String, Class<?>> m) throws SQLException { delegate.setTypeMap(m); }
    @Override public int    getHoldability()             throws SQLException { return delegate.getHoldability(); }
    @Override public void   setHoldability(int h)        throws SQLException { delegate.setHoldability(h); }
    @Override public boolean isValid(int timeout)        throws SQLException { return delegate.isValid(timeout); }
    @Override public void   setClientInfo(String n, String v) throws SQLClientInfoException { delegate.setClientInfo(n, v); }
    @Override public void   setClientInfo(Properties p)       throws SQLClientInfoException { delegate.setClientInfo(p); }
    @Override public String  getClientInfo(String name)  throws SQLException { return delegate.getClientInfo(name); }
    @Override public Properties getClientInfo()          throws SQLException { return delegate.getClientInfo(); }
    @Override public String  getSchema()                 throws SQLException { return delegate.getSchema(); }
    @Override public void   setSchema(String schema)     throws SQLException { delegate.setSchema(schema); }
    @Override public void   abort(Executor e)            throws SQLException { delegate.abort(e); }
    @Override public void   setNetworkTimeout(Executor e, int ms) throws SQLException { delegate.setNetworkTimeout(e, ms); }
    @Override public int    getNetworkTimeout()          throws SQLException { return delegate.getNetworkTimeout(); }
    @Override public Array  createArrayOf(String t, Object[] e) throws SQLException { return delegate.createArrayOf(t, e); }
    @Override public Blob   createBlob()                 throws SQLException { return delegate.createBlob(); }
    @Override public Clob   createClob()                 throws SQLException { return delegate.createClob(); }
    @Override public NClob  createNClob()                throws SQLException { return delegate.createNClob(); }
    @Override public SQLXML createSQLXML()               throws SQLException { return delegate.createSQLXML(); }
    @Override public Struct createStruct(String t, Object[] a) throws SQLException { return delegate.createStruct(t, a); }
    @Override public <T> T  unwrap(Class<T> iface)       throws SQLException { return delegate.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
}